
backend:
  name: github
  repo: vumc-media/vumc-website
  branch: main

media_folder: "vumc-media"
public_folder: "/vumc-media"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Button Text", name: "button_text", widget: "string" }
          - { label: "Button Link", name: "button_link", widget: "string" }
